# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TimeSeriesSAR3
                                 A QGIS plugin
 Visualize SAR Time Series for QGIS 3
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-08-18
        copyright            : (C) 2019 by Josef Kellndorfer / Earth Big Data LLC
        email                : kitsin@earthbigdata.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TimeSeriesSAR3 class from file TimeSeriesSAR3.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .timeseries_sar3 import TimeSeriesSAR3
    return TimeSeriesSAR3(iface)
